# This is a basic workflow to help you get started with Actions

name: Test String

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      version:
        description: Version Number
        required: true

jobs:
  test_string:
    runs-on: ubuntu-latest

    steps:
    
      - name: Checkout Repo
        uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Append to Readme
        run: echo "test" >> README.md

      - name: Commit Changes
        uses: actions-js/push@master
        with:
          message: ${{ format('Actions{0} Publish Version {1}', ':', inputs.version) }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
